CREATE DATABASE IF NOT EXISTS BCI-IOB_SQL;
USE BCI-IOB_SQ;
CREATE TABLE IF NOT EXISTS sensors (
  ts TIMESTAMP,
  temperature FLOAT,
  humidity FLOAT
) TAGS (device_id BINARY(20));

INSERT INTO sensors001 USING demo.sensors TAGS ('device001') VALUES (NOW, 27.1, 19.0);

SELECT * FROM sensors WHERE ts > NOW - 1h;
